<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <!-- Datos de tu proyecto padre -->
    <groupId>cl.duoc.colegio</groupId>
    <artifactId>backend</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <!-- ESTA ES LA PALABRA CLAVE QUE LE DICE A MAVEN QUE ES UNA CARPETA CONTENEDORA -->
    <packaging>pom</packaging>

    <name>colegio-backend</name>
    <description>Proyecto Multimódulo para el Colegio Bernardo O'Higgins</description>

    <!-- Aquí listamos las carpetas de tus microservicios -->
    <modules>
        <module>academic-service</module>
        <module>attendance-service</module>
        <module>communication-service</module>
        <module>bff-service</module>
    </modules>

</project>