spring.application.name=bff-service
server.port=8080

# JWT
jwt.secret=clave-super-secreta-del-colegio-ohiggins-2024
jwt.expiration=86400000

# Superadmin
admin.rut=11111111-1
admin.password=admin123

spring.security.user.name=disabled
spring.security.user.password=disabled

# URLs de microservicios
services.academic.url=http://localhost:8081
services.attendance.url=http://localhost:8082
services.communication.url=http://localhost:8083

# Circuit Breaker - academic-service
resilience4j.circuitbreaker.instances.academic-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.academic-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.academic-service.wait-duration-in-open-state=10s

# Circuit Breaker - attendance-service
resilience4j.circuitbreaker.instances.attendance-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.attendance-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.attendance-service.wait-duration-in-open-state=10s

# Circuit Breaker - communication-service (listo para cuando lo uses)
resilience4j.circuitbreaker.instances.communication-service.sliding-window-size=10
resilience4j.circuitbreaker.instances.communication-service.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.communication-service.wait-duration-in-open-state=10s
