spring.application.name=academic-service
server.port=8081

# Database
spring.datasource.url=jdbc:h2:file:./data/academicdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true

# Dialect warning fix
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# JPA
spring.jpa.open-in-view=false
